name: Gather
options:
  bundleIdPrefix: com.gather
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.2"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: false
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
    ENABLE_PREVIEWS: true

targets:
  Gather:
    type: application
    platform: iOS
    sources:
      - path: Gather
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gather.app
        INFOPLIST_KEY_CFBundleDisplayName: "Gather"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    entitlements:
      path: Gather/Gather.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.gather.app
        com.apple.developer.icloud-services:
          - CloudKit
        aps-environment: development
        com.apple.developer.applesignin:
          - Default
    dependencies: []
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed"
          fi
        basedOnDependencyAnalysis: false

  GatherTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GatherTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gather.app.tests
    dependencies:
      - target: Gather

  GatherUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: GatherUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gather.app.uitests
    dependencies:
      - target: Gather

schemes:
  Gather:
    build:
      targets:
        Gather: all
        GatherTests: [test]
        GatherUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - GatherTests
        - GatherUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
