name: Gather
options:
  bundleIdPrefix: ca.thebighead
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: false
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
    ENABLE_PREVIEWS: true

targets:
  Gather:
    type: application
    platform: iOS
    sources:
      - path: Gather
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ca.thebighead.gathr
        INFOPLIST_KEY_CFBundleDisplayName: "Gathr"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 7HTTY6JAP6
        CODE_SIGN_ENTITLEMENTS: Gather/Gather.entitlements
    info:
      path: Gather/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: "ca.thebighead.gathr"
            CFBundleURLSchemes:
              - gather
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCalendarsFullAccessUsageDescription: "Gather needs calendar access to add events to your calendar."
        NSContactsUsageDescription: "Gather needs access to your contacts to help you invite guests."
        NSPhotoLibraryUsageDescription: "Gather needs access to your photo library to add event photos."
    dependencies: []
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed"
          fi
        basedOnDependencyAnalysis: false

  GatherTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GatherTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ca.thebighead.gathr.tests
    dependencies:
      - target: Gather

  GatherUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: GatherUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ca.thebighead.gathr.uitests
    dependencies:
      - target: Gather

schemes:
  Gather:
    build:
      targets:
        Gather: all
        GatherTests: [test]
        GatherUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - GatherTests
        - GatherUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
